function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function applySettings(){document.documentElement.style.setProperty("--bg",settings.bg);document.documentElement.style.setProperty("--btn",settings.btn);document.documentElement.style.setProperty("--accent",settings.accent);document.body.classList.toggle("no-animations",!settings.animations);document.body.classList.toggle("no-effects",!settings.effects);document.getElementById("timingText").textContent=`${settings.open} – ${settings.close}`;document.getElementById("shopStatus").textContent=`Opening: ${settings.open} • Closing: ${settings.close} • Holiday: ${settings.holiday}`}
function renderProducts(){const q=(document.getElementById("searchProducts")?.value||"").toLowerCase();const list=products.filter(p=>`${p.name} ${p.type} ${p.condition}`.toLowerCase().includes(q));const grid=document.getElementById("productGrid");grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${p.images?.[0]?`<img src="${p.images[0]}" alt="${esc(p.name)}">`:`<div class="placeholder">Product image coming soon</div>`}</div><div class="product-body"><div class="product-meta"><span>${esc(p.type)}</span><span>${esc(p.condition)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.details||"Owner will provide complete details.")}</p><div class="price-row">${p.actual?`<span class="actual">₹${p.actual}</span>`:""}<span class="offer-price">₹${p.offer||p.actual||"Ask"}</span></div><button class="slide-buy" onclick="openBuyModal('${p.id}')">${settings.animations?"⇢ Slide / Buy":"Buy Now"}</button></div></article>`).join("");document.getElementById("emptyProducts").style.display=list.length?"none":"block"}
function renderOffers(){const grid=document.getElementById("offerGrid");grid.innerHTML=offers.map(o=>`<article class="offer-item">${o.image?`<img src="${o.image}" alt="${esc(o.title)}">`:""}<h3>${esc(o.title)}</h3><p>${esc(o.text)}</p></article>`).join("");document.getElementById("emptyOffers").style.display=offers.length?"none":"block"}
function renderServices(){document.getElementById("serviceGrid").innerHTML=DEFAULT_SERVICES.map(s=>`<article class="service-card"><h3>${s.title}</h3><p>${s.text}</p><a class="btn btn-outline" href="https://wa.me/916360509055?text=${encodeURIComponent("Hello Charan Mobiles, I want information about "+s.title)}" target="_blank" rel="noopener">Ask on WhatsApp</a></article>`).join("")}
function openBuyModal(id){selectedProduct=products.find(p=>p.id===id);if(!selectedProduct)return;document.getElementById("buyProductName").textContent=selectedProduct.name;document.getElementById("buyModal").classList.remove("hidden")}
function closeBuyModal(){document.getElementById("buyModal").classList.add("hidden")}
function sendWhatsAppEnquiry(){const n=document.getElementById("customerName").value.trim(),p=document.getElementById("customerPhone").value.trim(),l=document.getElementById("customerPlace").value.trim();if(!n||!p||!l){alert("Please enter name, phone number and place.");return}const price=selectedProduct.offer||selectedProduct.actual||"Ask for price";const msg=`Hello Charan Mobiles,%0A%0AI am interested in:%0AProduct: ${encodeURIComponent(selectedProduct.name)}%0APrice: ₹${price}%0ACondition: ${selectedProduct.condition}%0A%0AMy Name: ${encodeURIComponent(n)}%0APhone: ${encodeURIComponent(p)}%0APlace: ${encodeURIComponent(l)}%0A%0APlease provide more information.`;window.open(`https://wa.me/916360509055?text=${msg}`,"_blank","noopener");closeBuyModal()}
function openMaps(){window.open("https://maps.app.goo.gl/bKs9CdG2TAaKtRuy5?g_st=ac","_blank","noopener")}
function requestBill(){const phone=document.getElementById("billPhone").value.trim(),bill=document.getElementById("billNo").value.trim();if(!phone||!bill){alert("Enter phone number and bill number.");return}const msg=`Hello Charan Mobiles, I want my E-Bill.%0APhone: ${encodeURIComponent(phone)}%0ABill No: ${encodeURIComponent(bill)}`;window.open(`https://wa.me/916360509055?text=${msg}`,"_blank","noopener")}
function closeOfferPopup(){document.getElementById("offerPopup").classList.add("hidden")}
function maybeShowPopup(){const o=offers.find(x=>x.popup);if(!o)return;document.getElementById("popupOfferContent").innerHTML=`${o.image?`<img src="${o.image}" alt="${esc(o.title)}">`:""}<h2>${esc(o.title)}</h2><p>${esc(o.text)}</p><a class="btn btn-light" href="#offers" onclick="closeOfferPopup()">View Offers</a>`;setTimeout(()=>document.getElementById("offerPopup").classList.remove("hidden"),900)}
document.getElementById("year").textContent=new Date().getFullYear();
applySettings();renderProducts();renderOffers();renderServices();maybeShowPopup();