const WA="916360509055",MAP="https://maps.app.goo.gl/bKs9CdG2TAaKtRuy5?g_st=ac",$=id=>document.getElementById(id);const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
function safeImage(src,alt=""){return src?`<img src="${esc(src)}" alt="${esc(alt)}" loading="lazy">`:""}
function applySettings(){const r=document.documentElement;r.style.setProperty("--bg",settings.bg);r.style.setProperty("--btn",settings.btn);r.style.setProperty("--accent",settings.accent);document.body.classList.toggle("no-animations",!settings.animations);document.body.classList.toggle("no-effects",!settings.effects);$("hours").textContent=`${settings.open} – ${settings.close}`;if(settings.qr)$("qrImage").src=settings.qr;$("shopInfo").textContent=`Open ${settings.open} – ${settings.close} · Holiday: ${settings.holiday}${settings.leave?" · "+settings.leave:""}`}
function gallery(images=[],alt=""){if(!images.length)return"";const gid="g"+Math.random().toString(36).slice(2);return `<div id="${gid}" class="gallery-main">${safeImage(images[0],alt)}</div>${images.length>1?`<div class="thumbs">${images.map(x=>`<img src="${esc(x)}" alt="" onclick="document.querySelector('#${gid} img').src=this.src">`).join("")}</div>`:""}`}
function makeAction(el,label,done,normal){if(!settings.animations){el.innerHTML=`<button class="btn light" type="button">${normal}</button>`;el.firstElementChild.onclick=done;return}el.innerHTML=`<div class="slider" role="button" tabindex="0"><span>${label}</span><b class="slider-knob">›</b></div>`;const s=el.firstElementChild,k=s.querySelector("b");let start=0,drag=false,doneOnce=false;s.onpointerdown=e=>{drag=true;start=e.clientX-k.getBoundingClientRect().left;s.setPointerCapture(e.pointerId)};s.onpointermove=e=>{if(!drag||doneOnce)return;const max=s.clientWidth-k.clientWidth-8,x=Math.max(4,Math.min(max,e.clientX-s.getBoundingClientRect().left-start));k.style.transform=`translateX(${x}px)`;if(x>max*.86){doneOnce=true;drag=false;k.style.transform=`translateX(${max}px)`;setTimeout(done,120)}};s.onpointerup=()=>{drag=false;if(!doneOnce)k.style.transform="translateX(0)"}}
function renderReachActions(){makeAction($("heroReach"),"Slide to Reach",()=>window.open(MAP,"_blank","noopener"),"Get Directions");makeAction($("contactReach"),"Slide to Reach",()=>window.open(MAP,"_blank","noopener"),"Get Directions")}
function renderProducts(){const q=($("search").value||"").toLowerCase(),list=products.filter(p=>`${p.name} ${p.type} ${p.condition}`.toLowerCase().includes(q));$("productGrid").innerHTML=list.map(p=>`<article class="card">${gallery(p.images,p.name)}<div class="card-body"><small>${esc(p.type)} · ${esc(p.condition)}</small><h3>${esc(p.name)}</h3><p>${esc(p.details||"")}</p><p>Stock: ${p.stock}</p><strong>${p.offer?"₹"+esc(p.offer):p.actual?"₹"+esc(p.actual):"Ask price"}</strong><div id="buy-${p.id}"></div></div></article>`).join("");list.forEach(p=>makeAction($("buy-"+p.id),"Slide to Buy",()=>openBuy(p.id),"Buy Now"));$("noProducts").hidden=!!list.length}
function renderOffers(){$("offerGrid").innerHTML=offers.map(o=>`<article class="card">${gallery(o.images,o.title)}<div class="card-body"><h3>${esc(o.title)}</h3><p>${esc(o.text||"")}</p></div></article>`).join("");$("noOffers").hidden=!!offers.length}
function renderServices(){$("serviceGrid").innerHTML=services.map(s=>`<article class="card service-card">${safeImage(s.image,s.title)}<div class="card-body"><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><a class="btn ghost" target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent("Hello Charan Mobiles, I want information about "+s.title)}">Ask on WhatsApp</a></div></article>`).join("")}
function openBuy(id){selectedProduct=products.find(p=>p.id===id);if(!selectedProduct)return;$("buyTitle").textContent=selectedProduct.name;$("buyModal").hidden=false;makeAction($("buyAction"),"Slide to Continue",sendEnquiry,"Continue to WhatsApp")}function closeBuy(){$("buyModal").hidden=true}function sendEnquiry(){const n=$("customerName").value.trim(),ph=$("customerPhone").value.trim(),pl=$("customerPlace").value.trim();if(!n||!ph||!pl)return alert("Enter your name, phone number and place.");const m=`Hello Charan Mobiles,%0A%0AProduct: ${selectedProduct.name}%0AName: ${n}%0APhone: ${ph}%0APlace: ${pl}`;window.open(`https://wa.me/${WA}?text=${m}`,"_blank","noopener");closeBuy()}
function closeOffer(){$("offerPopup").hidden=true}function maybePopup(){const o=offers.find(x=>x.popup);if(!o)return;$("popupContent").innerHTML=`${gallery(o.images,o.title)}<h2>${esc(o.title)}</h2><p>${esc(o.text||"")}</p>`;setTimeout(()=>$("offerPopup").hidden=false,700)}
async function lookupPublicBill(){const phone=$("billLookupPhone").value.replace(/\D/g,""),number=$("billLookupNumber").value.trim(),msg=$("billLookupMessage");if(!phone&&!number)return msg.textContent="Enter phone number or invoice number.";try{const b=await api(`/api/public/bills/lookup?phone=${encodeURIComponent(phone)}&number=${encodeURIComponent(number)}`);msg.innerHTML=`Bill found: <b>${esc(b.number)}</b>. <a class="btn light" href="/api/public/bills/${b.id}/pdf">Download PDF</a>`}catch{msg.textContent="Bill not found."}}
(async()=>{try{await publicLoad();applySettings();renderReachActions();renderProducts();renderOffers();renderServices();maybePopup();$("year").textContent=new Date().getFullYear()}catch(e){console.error(e);alert("Unable to load live shop data. Check server configuration.")}})();
