import bcrypt from "bcryptjs";import { randomUUID, createHash, randomBytes } from "crypto";import { eq, lt } from "drizzle-orm";import { getCookie,setCookie,deleteCookie } from "hono/cookie";import type { Context, Next } from "hono";import { db } from "./db";import { owner,sessions } from "./schema";
const COOKIE="cm_owner_session",hash=(s:string)=>createHash("sha256").update(s).digest("hex");
const attempts=new Map<string,{n:number,until:number}>();
export async function seedOwner(){const existing=await db.select().from(owner).limit(1);if(existing.length)return;const p=process.env.CHARAN_OWNER_PASSWORD;if(!p||p.startsWith("SET_"))throw new Error("Set CHARAN_OWNER_PASSWORD before first startup");await db.insert(owner).values({id:"owner",passwordHash:await bcrypt.hash(p,12),createdAt:Date.now()})}
export async function login(c:Context,password:string){const forwarded=c.req.header("x-forwarded-for");const ip=forwarded?forwarded.split(",")[0].trim():(c.req.header("cf-connecting-ip")||"local");const a=attempts.get(ip);if(a&&a.until>Date.now())return {ok:false,error:"Too many attempts. Try later."};const row=(await db.select().from(owner).where(eq(owner.id,"owner")).limit(1))[0];if(!row||!(await bcrypt.compare(password,row.passwordHash))){const n=(a?.n||0)+1;attempts.set(ip,n>=5?{n,until:Date.now()+15*60_000}:{n,until:0});return {ok:false,error:"Invalid credentials"}}attempts.delete(ip);const token=randomBytes(32).toString("base64url"),id=randomUUID(),expires=Date.now()+7*24*3600_000;await db.insert(sessions).values({id,tokenHash:hash(token),expiresAt:expires,createdAt:Date.now()});setCookie(c,COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"Strict",path:"/",maxAge:7*24*3600});return {ok:true}}
export async function requireOwner(c:Context,next:Next){const token=getCookie(c,COOKIE);if(!token)return c.json({error:"Unauthorized"},401);const s=(await db.select().from(sessions).where(eq(sessions.tokenHash,hash(token))).limit(1))[0];if(!s||s.expiresAt<Date.now()){if(token)deleteCookie(c,COOKIE,{path:"/"});return c.json({error:"Session expired"},401)}await next()}
export async function logout(c:Context){const token=getCookie(c,COOKIE);if(token)await db.delete(sessions).where(eq(sessions.tokenHash,hash(token)));deleteCookie(c,COOKIE,{path:"/"})}
export async function changePassword(current:string,next:string){if(next.length<10)throw new Error("New password must be at least 10 characters");const row=(await db.select().from(owner).where(eq(owner.id,"owner")).limit(1))[0];if(!row||!(await bcrypt.compare(current,row.passwordHash)))throw new Error("Current password is incorrect");await db.update(owner).set({passwordHash:await bcrypt.hash(next,12)}).where(eq(owner.id,"owner"));await db.delete(sessions)}
export async function cleanupSessions(){await db.delete(sessions).where(lt(sessions.expiresAt,Date.now()))}
