import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
export const owner=sqliteTable("owner",{id:text("id").primaryKey(),passwordHash:text("password_hash").notNull(),createdAt:integer("created_at").notNull()});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()});
export const products=sqliteTable("products",{id:text("id").primaryKey(),name:text("name").notNull(),type:text("type").notNull(),stock:integer("stock").notNull(),actual:text("actual"),offer:text("offer"),condition:text("condition").notNull(),details:text("details"),damage:text("damage"),images:text("images",{mode:"json"}).$type<string[]>().notNull(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const offers=sqliteTable("offers",{id:text("id").primaryKey(),title:text("title").notNull(),text:text("text"),images:text("images",{mode:"json"}).$type<string[]>().notNull(),popup:integer("popup",{mode:"boolean"}).notNull(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const services=sqliteTable("services",{id:text("id").primaryKey(),title:text("title").notNull(),text:text("text").notNull(),image:text("image"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const settings=sqliteTable("settings",{key:text("key").primaryKey(),value:text("value",{mode:"json"}).$type<any>().notNull(),updatedAt:integer("updated_at").notNull()});
export const bills=sqliteTable("bills",{id:text("id").primaryKey(),number:text("number").notNull().unique(),date:text("date").notNull(),time:text("time").notNull(),customer:text("customer").notNull(),phone:text("phone").notNull(),address:text("address"),items:text("items",{mode:"json"}).$type<any[]>().notNull(),discount:text("discount").notNull(),other:text("other").notNull(),status:text("status").notNull(),subtotal:text("subtotal").notNull(),total:text("total").notNull(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const reminders=sqliteTable("reminders",{id:text("id").primaryKey(),name:text("name").notNull(),phone:text("phone").notNull(),type:text("type").notNull(),english:text("english").notNull(),kannada:text("kannada").notNull(),includeQr:integer("include_qr",{mode:"boolean"}).notNull(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
